src/RSTracker/Controllers/CircularsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RSTracker.Models;
using HSTrackerModel.Models;
using HSTrackerService.Interface;

namespace RSTracker.Controllers
{
    [Authorize()]
    public class CircularsController : Controller
    {
        private readonly ICircularService circularService;
        private readonly IRequisitionService requisitionService;
        public CircularsController(IRequisitionService requisitionService, ICircularService circularService)
        {
            this.circularService = circularService;
            this.requisitionService = requisitionService;
        }

        // GET: Circulars
        public ActionResult Index(int? requisitionId)
        {
            var circular = circularService.GetAllCircular(requisitionId);

            return View(circular);
        }

        // GET: Circulars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var circular = circularService.GetCircular(id);
            if (circular == null)
            {
                return HttpNotFound();
            }
            return View(circular);
        }

        // GET: Circulars/Create
        public ActionResult Create()
        {
            ViewBag.RequisitionId = new SelectList(requisitionService.GetAllRequisition(), "Id", "RefNo");
            return View();
        }

        // POST: Circulars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Circular circular)
        {
            if (ModelState.IsValid)
            {
                circularService.CreateCircular(circular);
                circularService.SaveCircular();
                return RedirectToAction("Index");
            }

            ViewBag.RequisitionId = new SelectList(requisitionService.GetAllRequisition(), "Id", "RefNo", circular.RequisitionId);
            return View(circular);
        }

        // GET: Circulars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Circular circular = circularService.GetCircular(id);
            if (circular == null)
            {
                return HttpNotFound();
            }
            ViewBag.RequisitionId = new SelectList(requisitionService.GetAllRequisition(), "Id", "RefNo", circular.RequisitionId);
            return View(circular);
        }

        // POST: Circulars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Circular circular)
        {
            if (ModelState.IsValid)
            {
                circularService.EditCircular(circular);
                circularService.SaveCircular();
                return RedirectToAction("Index");
            }
            ViewBag.RequisitionId = new SelectList(requisitionService.GetAllRequisition(), "Id", "RefNo", circular.RequisitionId);
            return View(circular);
        }

        // GET: Circulars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Circular circular = circularService.GetCircular(id);
            if (circular == null)
            {
                return HttpNotFound();
            }
            return View(circular);
        }

        // POST: Circulars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Circular circular = circularService.GetCircular(id);
            circularService.DeleteCircular(circular);
            circularService.SaveCircular();
            return RedirectToAction("Index");
        }

    }
}

src/RSTracker/Controllers/HomeController.cs
using HSTrackerService.Interface;
using RSTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RSTracker.Controllers
{
    [Authorize()]
    public class HomeController : Controller
    {
        private readonly IRequisitionService requisitionService;
        public HomeController(IRequisitionService requisitionService)
        {
            this.requisitionService = requisitionService;
        }
        public ActionResult Index()
        {
            var requisitions = requisitionService.GetAllRequisition();
            //.Include(r => r.Dep).Include(r => r.Designation).Include(r => r.Div).Include(r => r.Emp).Include(r => r.Employee).Include(r => r.Stat).Include(r => r.SubUni);
            return View(requisitions.Where(p => p.StatusId !=3).OrderBy(p => p.RequisitionDate).ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/RSTracker/Views/Home/About.cshtml
<h3>About RSTracker</h3>
<p>Recruitment selection tracker known as RStracker is an web page application to tracke HR recruitment information.</p>

<h4>Project Features</h4>
<ul>
    <li> Requisition</li>
    <li> Circular</li>
    <li> Employee Information</li>
    <li> Authentication and Authorization</li>
</ul>
<b>Design and developed by</b>
<p>Khaleda Islam <br />
    Email   : khaleda.islam@leads-bd.com <br />
    Linkdin : https://www.linkedin.com/in/khaledaislam </p>

<p>
    Md. Aftab Uddin Kajal <br />
    Email   : kajal.alpha@gmail.com <br />
    Linkdin : https://www.linkedin.com/in/iamkajal
</p>
<b>Powered by</b>
<p>Leadsoft Bangladesh Limited <br />
Add :  Rupayan Trade Center, 114 Kazi Nazrul Islam Ave, Dhaka 1205 <br />
Web :  www.leads-bd.com </p>

src/RSTracker/Views/Home/Contact.cshtml
<h3>Contact By</h3>
<p>
    Leadsoft Bangladesh Limited <br />
    Add :  Rupayan Trade Center, 114 Kazi Nazrul Islam Ave, Dhaka 1205 <br />
    Web :  www.leads-bd.com
</p>




<address>
    <strong>Support:</strong>   <a href="khaleda.islam@leads-bd.com">khaleda.islam@leads-bd.com</a><br />
    <strong>Phone</strong> : 01775983593
</address>

src/RSTracker/Views/Home/Index.cshtml
@model IEnumerable<HSTrackerModel.Models.Requisition>

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active"><h4>Dash Board</h4></li>
</ol>


<table class="table table-hover table-striped" id="dataTable">
    <thead class="thead-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RefNo)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.DeptId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation.Name)
            </th>

            @*<th>
                    @Html.DisplayNameFor(model => model.Division.Name)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.RequiredByEmp.Name)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.RaisedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status.Name)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.SubUnit.Name)
                </th>*@

            <th>
                @Html.DisplayNameFor(model => model.RequisitionDate)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.VacancyTypeId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastWorkingDay)
                </th>*@
            <th>Circular</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RefNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dept.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designation.Name)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Division.Name)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.RequiredByEmp.Name)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.SubUnit.Name)
                </td>*@

            <td>
                @Html.DisplayFor(modelItem => item.RequisitionDate)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.VacancyTypeId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastWorkingDay)
                </td>*@
            <td>
                @Html.ActionLink("View", "Index", "Circulars", new { requisitionId = item.Id }, null)
            </td>
            <td>
             
                @Html.ActionLink("Details", "Details", new { id = item.Id }) 
              
            </td>
        </tr>
    }

</table>